<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnMasTarde</name>
   <tag></tag>
   <elementGuidId>386867aa-d76a-48ba-8e0e-2babcf875437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div/div[2]/div/div/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div/div/div[2]/div/div/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Más tarde</value>
      <webElementGuid>c9ebf192-359b-4249-b1b0-123daa8d454d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>ca9b6f75-12c0-4090-96dc-05e38a385ebc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
