<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Entendido_Cookies</name>
   <tag></tag>
   <elementGuidId>fc8b972f-ebec-40cb-8cf9-a320e981a549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.cookie-consent-banner-opt-out__action.cookie-consent-banner-opt-out__action--primary.cookie-consent-banner-opt-out__action--key-accept</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Entendido' or . = 'Entendido')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bfdfdd0a-8b5a-40eb-a6bf-c9bc62dde64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c7efcf8-4021-487e-936e-b21222b35818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>action:understood-button</value>
      <webElementGuid>39affebc-e7df-4e6b-9a2b-3d756327e022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookie-consent-banner-opt-out__action cookie-consent-banner-opt-out__action--primary cookie-consent-banner-opt-out__action--key-accept</value>
      <webElementGuid>2f7cd6be-4f9c-468a-bf31-b3885368bfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entendido</value>
      <webElementGuid>a06b51d9-673b-4f32-b498-5e36e3fa5976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[2]/div[@class=&quot;cookie-consent-banner-opt-out&quot;]/div[@class=&quot;cookie-consent-banner-opt-out__actions&quot;]/button[@class=&quot;cookie-consent-banner-opt-out__action cookie-consent-banner-opt-out__action--primary cookie-consent-banner-opt-out__action--key-accept&quot;]</value>
      <webElementGuid>9390d473-9aec-457f-b9e8-bf3f3035c24b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>c8a31399-699e-4807-995b-ae472bbf190f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='personalizar tu experiencia'])[1]/following::button[1]</value>
      <webElementGuid>3ca5b708-9260-4e33-8efb-730ba115ac56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este sitio usa cookies'])[1]/following::button[1]</value>
      <webElementGuid>fd5ed13a-7876-4d3b-8a8c-c4c0ff888f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurar cookies'])[1]/preceding::button[1]</value>
      <webElementGuid>32f368b6-02e8-4a81-a20a-4b5cf38b939c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Listo! Guardamos tus preferencias.'])[1]/preceding::button[2]</value>
      <webElementGuid>4ca51932-9d1f-4fae-acaa-732464d8a3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entendido']/parent::*</value>
      <webElementGuid>06dfb13f-5556-4914-8d66-60837e602fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>cbe219d7-b6bb-4545-b4ae-8ff2f7d112b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Entendido' or . = 'Entendido')]</value>
      <webElementGuid>87db04c8-90c1-4a32-8abc-054dc01de6a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
