<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown</name>
   <tag></tag>
   <elementGuidId>b6be6dda-e5ec-41be-94ae-a262d195480f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.andes-dropdown__standalone-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Más relevantes'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>28eca599-e3b3-4eaf-97ff-ebb3056a9034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>andes-dropdown__standalone-arrow</value>
      <webElementGuid>ed58bf2f-9fcb-4717-86bb-7fab347201c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>4c53c369-9e89-4869-bb30-ee1cb157fb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>85d93669-6411-47cf-b3c0-ea0bdfd6ea14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 12 12</value>
      <webElementGuid>6969bd83-b0fb-4e55-b972-73b1c0459a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>71275f1c-9737-4c32-b7d4-961d588fae34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;ui-search shops__ui-main&quot;]/div[@class=&quot;ui-search-main ui-search-main--without-header shops__search-main&quot;]/section[@class=&quot;ui-search-results ui-search-results--without-disclaimer shops__search-results&quot;]/div[@class=&quot;ui-search-view-options__container&quot;]/div[@class=&quot;ui-search-view-options shops__view-options&quot;]/div[@class=&quot;ui-search-view-options__content&quot;]/div[@class=&quot;ui-search-view-options__group&quot;]/div[@class=&quot;ui-search-sort-filter shops__sort-filter&quot;]/div[@class=&quot;andes-dropdown andes-dropdown--standalone ui-search-sort-filter__dropdown andes-dropdown--compact&quot;]/div[@class=&quot;andes-floating-menu&quot;]/button[@class=&quot;andes-dropdown__trigger&quot;]/svg[@class=&quot;andes-dropdown__standalone-arrow&quot;]</value>
      <webElementGuid>3b0a21e4-4a4a-47a7-b47b-0484b27c6324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Más relevantes'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>c7ef4a63-b84a-4acc-8762-aaae32b6db63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordenar por'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>13b7767c-4353-4121-8f63-89e917815107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samsung'])[3]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>331b5ca2-5b96-420e-9ee1-b5b584a71eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daewoo'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7e4dbfd0-4107-4e12-bb12-94c797c6897a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
