<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>primerPrecioObj</name>
   <tag></tag>
   <elementGuidId>bae2c6ce-441e-465d-a005-f6c225846494</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.price-tag-fraction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='root-app']/div/div[2]/section/ol/li/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f81c2a9-d2f7-47ee-966e-bdcf4153482d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price-tag-fraction</value>
      <webElementGuid>ed6bf39c-bd31-450b-9436-e3d312292d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>599</value>
      <webElementGuid>24ce3edd-ad0c-4ef6-b948-73a6e891dda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;ui-search shops__ui-main&quot;]/div[@class=&quot;ui-search-main ui-search-main--without-header shops__search-main&quot;]/section[@class=&quot;ui-search-results ui-search-results--without-disclaimer shops__search-results&quot;]/ol[@class=&quot;ui-search-layout ui-search-layout--stack shops__layout&quot;]/li[@class=&quot;ui-search-layout__item shops__layout-item&quot;]/div[@class=&quot;ui-search-result__wrapper shops__result-wrapper&quot;]/div[@class=&quot;andes-card andes-card--flat andes-card--default ui-search-result shops__cardStyles ui-search-result--core andes-card--padding-default&quot;]/div[@class=&quot;ui-search-result__content-wrapper shops__result-content-wrapper&quot;]/div[@class=&quot;ui-search-result__content-columns shops__content-columns&quot;]/div[@class=&quot;ui-search-result__content-column ui-search-result__content-column--left shops__content-columns-left&quot;]/div[@class=&quot;ui-search-item__group ui-search-item__group--price shops__items-group&quot;]/div[@class=&quot;ui-search-item__group__element shops__items-group-details&quot;]/div[@class=&quot;ui-search-price ui-search-price--size-medium shops__price&quot;]/div[@class=&quot;ui-search-price__second-line shops__price-second-line&quot;]/span[@class=&quot;price-tag ui-search-price__part shops__price-part&quot;]/span[@class=&quot;price-tag-amount&quot;]/span[@class=&quot;price-tag-fraction&quot;]</value>
      <webElementGuid>5d7e885f-18e1-4afb-9278-55729d6235e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root-app']/div/div[2]/section/ol/li/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      <webElementGuid>49d9299e-58b4-4915-887e-f66f3ad06608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/following::span[1]</value>
      <webElementGuid>436086ca-c22d-4213-a2ac-d6888389bb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cable Carga Usb A Microusb V8 Para Samsung LG Nokia 1.5mt'])[1]/following::span[5]</value>
      <webElementGuid>57dcbc66-4658-46ac-9e49-9dda55a9ef57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Llega mañana'])[1]/preceding::span[2]</value>
      <webElementGuid>57c8eb6f-aae2-4cac-88c0-63fd99e36cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cable Micro Usb Rápido 1 Mts Samsung J1 J2 J3 J4 J5 J6 J7 +'])[1]/preceding::span[6]</value>
      <webElementGuid>073b83e9-44b0-4478-80c3-fbd8c5b2911c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='599']/parent::*</value>
      <webElementGuid>43d059db-ac22-49ee-9e8a-0c3008386a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span[2]</value>
      <webElementGuid>81ff8bc6-e70e-4d7f-9d90-4664d53f3e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '599' or . = '599')]</value>
      <webElementGuid>bfa1de2c-471c-4597-b6f7-76b01308f46b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
