<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SAMSUNG</name>
   <tag></tag>
   <elementGuidId>4a4693b9-bd27-4ea4-a025-e3f619435da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='special']/a/div/div/div[2]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>1087549b-48ae-47fc-8c80-fc5924c4a616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>e43ee226-066e-43a4-a8b1-62e752227425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAMSUNG</value>
      <webElementGuid>4a34efd6-0956-4bb0-b75b-d8ec11983386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;default hub&quot;]/div[2]/section[@class=&quot;hub__boxed-width&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;splinter-row special__grid-containerx3 special__containerx3&quot;]/div[@id=&quot;special&quot;]/a[1]/div[1]/div[@class=&quot;andes-card andes-card--flat andes-card--default hub__grid-item item__banner banner__label andes-card--padding-default andes-card--animated&quot;]/div[@class=&quot;label&quot;]/h3[@class=&quot;title&quot;]</value>
      <webElementGuid>9f66c146-903b-4bfd-9f00-8ff29bbc86ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='special']/a/div/div/div[2]/h3</value>
      <webElementGuid>6148d262-cb9e-4fd0-814c-dde5483b48b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPRÁ POR MARCA'])[1]/following::h3[1]</value>
      <webElementGuid>b7940b30-9fbe-423f-b8ce-8d01323b957d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capital Federal'])[2]/following::h3[1]</value>
      <webElementGuid>e0a90f20-fef2-46a6-9f84-0321555f17ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLE'])[1]/preceding::h3[1]</value>
      <webElementGuid>91a083b1-7683-40f2-9aa9-4974c2f0e34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOTOROLA'])[1]/preceding::h3[2]</value>
      <webElementGuid>46a60edf-56af-42df-b392-75f447ec8715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SAMSUNG']/parent::*</value>
      <webElementGuid>bcb4d1e5-223c-471c-a371-d12bf957b9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h3</value>
      <webElementGuid>bbb57055-4c09-4346-872e-138a49bc2fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'SAMSUNG' or . = 'SAMSUNG')]</value>
      <webElementGuid>7761e8db-f249-4680-96cc-17225943f87c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
