<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>segundoPrecioObj</name>
   <tag></tag>
   <elementGuidId>23c0a932-a8e9-4aa4-b096-2e8c8e5c0057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='root-app']/div/div[2]/section/ol/li[2]/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d842cc5e-0af6-4002-98a7-1f93b4369659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price-tag-fraction</value>
      <webElementGuid>0fe3b8d0-c587-42e4-9048-800f6dbb923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>715</value>
      <webElementGuid>132ef59f-0967-46c4-85f0-7b5a00488996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;ui-search shops__ui-main&quot;]/div[@class=&quot;ui-search-main ui-search-main--without-header shops__search-main&quot;]/section[@class=&quot;ui-search-results ui-search-results--without-disclaimer shops__search-results&quot;]/ol[@class=&quot;ui-search-layout ui-search-layout--stack shops__layout&quot;]/li[@class=&quot;ui-search-layout__item shops__layout-item&quot;]/div[@class=&quot;ui-search-result__wrapper shops__result-wrapper&quot;]/div[@class=&quot;andes-card andes-card--flat andes-card--default ui-search-result shops__cardStyles ui-search-result--core andes-card--padding-default&quot;]/div[@class=&quot;ui-search-result__content-wrapper shops__result-content-wrapper&quot;]/div[@class=&quot;ui-search-result__content-columns shops__content-columns&quot;]/div[@class=&quot;ui-search-result__content-column ui-search-result__content-column--left shops__content-columns-left&quot;]/div[@class=&quot;ui-search-item__group ui-search-item__group--price shops__items-group&quot;]/div[@class=&quot;ui-search-item__group__element shops__items-group-details&quot;]/div[@class=&quot;ui-search-price ui-search-price--size-medium shops__price&quot;]/div[@class=&quot;ui-search-price__second-line shops__price-second-line&quot;]/span[@class=&quot;price-tag ui-search-price__part shops__price-part&quot;]/span[@class=&quot;price-tag-amount&quot;]/span[@class=&quot;price-tag-fraction&quot;]</value>
      <webElementGuid>0742063a-cae7-47d6-9940-4cbeedb580ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root-app']/div/div[2]/section/ol/li[2]/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      <webElementGuid>dab7dcc5-5efc-42bd-b7db-60e54ac94b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/following::span[1]</value>
      <webElementGuid>b6c6f530-4625-474e-8d74-8c5413639e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cable Micro Usb Rápido 1 Mts Samsung J1 J2 J3 J4 J5 J6 J7 +'])[1]/following::span[5]</value>
      <webElementGuid>a50018e2-0f0f-419f-aad4-bb2d54d13d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Llega mañana'])[2]/preceding::span[2]</value>
      <webElementGuid>6404d0ac-3e88-4343-a13f-b0352c283d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cable Micro Usb Carga Rapida 2 Metros Para Samsung Motorola'])[1]/preceding::span[6]</value>
      <webElementGuid>b7c8b6ea-bc72-4292-81f8-b3e3f96fc0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='715']/parent::*</value>
      <webElementGuid>a6244a17-9215-456a-85d1-53402e6c8ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      <webElementGuid>99b4a2c0-1733-4716-991f-f3f675f846eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '715' or . = '715')]</value>
      <webElementGuid>c1f1cfbe-dc66-411e-bde4-84d268721f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
