<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ultimoPrecioObj</name>
   <tag></tag>
   <elementGuidId>4a4ee136-c57c-43cf-94b6-b7fff29d70d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='root-app']/div/div[2]/section/ol/li[50]/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05cda41a-0dec-466f-8699-4e6888efca1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price-tag-fraction</value>
      <webElementGuid>76e41a41-c326-40e8-bb37-ca04436e8e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7.999</value>
      <webElementGuid>e9bb61e2-41da-4275-86b6-5bab0d78efdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root-app&quot;)/div[@class=&quot;ui-search shops__ui-main&quot;]/div[@class=&quot;ui-search-main ui-search-main--without-header shops__search-main&quot;]/section[@class=&quot;ui-search-results ui-search-results--without-disclaimer shops__search-results&quot;]/ol[@class=&quot;ui-search-layout ui-search-layout--stack shops__layout&quot;]/li[@class=&quot;ui-search-layout__item shops__layout-item&quot;]/div[@class=&quot;ui-search-result__wrapper shops__result-wrapper&quot;]/div[@class=&quot;andes-card andes-card--flat andes-card--default ui-search-result shops__cardStyles ui-search-result--core andes-card--padding-default&quot;]/div[@class=&quot;ui-search-result__content-wrapper shops__result-content-wrapper&quot;]/div[@class=&quot;ui-search-result__content-columns shops__content-columns&quot;]/div[@class=&quot;ui-search-result__content-column ui-search-result__content-column--left shops__content-columns-left&quot;]/div[@class=&quot;ui-search-item__group ui-search-item__group--price shops__items-group&quot;]/div[@class=&quot;ui-search-item__group__element shops__items-group-details&quot;]/div[@class=&quot;ui-search-price ui-search-price--size-medium shops__price&quot;]/div[@class=&quot;ui-search-price__second-line shops__price-second-line&quot;]/span[@class=&quot;price-tag ui-search-price__part shops__price-part&quot;]/span[@class=&quot;price-tag-amount&quot;]/span[@class=&quot;price-tag-fraction&quot;]</value>
      <webElementGuid>ce6eb068-9f96-4d62-b587-cb102f7a9012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='root-app']/div/div[2]/section/ol/li[50]/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      <webElementGuid>f5a65515-8ca2-48f6-b245-8a95f9b5af4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[55]/following::span[1]</value>
      <webElementGuid>2e3a7947-9b93-494e-bafb-e431c9064d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/preceding::span[6]</value>
      <webElementGuid>543ee11e-34cc-4049-82b2-a3893373342e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[50]/div/div/div[2]/div[2]/div/div/div/div/div/span/span[2]/span[2]</value>
      <webElementGuid>0243bbeb-cf10-434d-ba91-f82330acbd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '7.999' or . = '7.999')]</value>
      <webElementGuid>eb972955-58c3-461d-9d86-fb8f3351b7f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
